version: '2.4'
services:
  # client-main:
  #   build:
  #     context: ./client/main
  #   container_name: one-client-main
  #   ports:
  #     - 3000:3000
  #   stdin_open: true
  #   volumes:
  #     - ./client/main:/usr/src/app
  #     - /usr/src/app/node_modules/
  # db-mysql-initiative:
  #   command: --default-authentication-plugin=mysql_native_password
  #   container_name: one-db-mysql-initiative
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: main
  #   healthcheck:
  #     test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
  #     timeout: 20s
  #     retries: 10
  #   image: mysql
  db-mysql-user:
    command: --default-authentication-plugin=mysql_native_password
    container_name: one-db-mysql-user
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: main
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    image: mysql
  # ds-main:
  #   build:
  #     context: ./ds/main
  #   container_name: one-ds-main
  #   ports:
  #     - 6006:6006
  #   volumes:
  #     - ./ds/main:/usr/src/app
  #     - /usr/src/app/node_modules/
  # server-initiative:
  #   build:
  #     context: ./server/initiative
  #   container_name: one-server-initiative
  #   depends_on:
  #     db-mysql-initiative:
  #       condition: service_healthy
  #   ports:
  #     - 9001:3000
  #   volumes:
  #     - ./server/initiative:/usr/src/app
  #     - /usr/src/app/node_modules/
  server-user:
    build:
      context: ./server/user
    container_name: one-server-user
    depends_on:
      db-mysql-user:
        condition: service_healthy
    environment:
      DB_HOST: db-mysql-user
    ports:
      - 9002:3000
    volumes:
      - ./server/user:/usr/src/app
      - /usr/src/app/node_modules/
  server-gateway:
    build:
      context: ./server/gateway
    container_name: one-server-gateway
    depends_on:
      - server-user
    environment:
      SERVER_USER_HOST: server-user
    ports:
      - 9000:3000
    volumes:
      - ./server/gateway:/usr/src/app
      - /usr/src/app/node_modules/
      