version: '2.4'
services:
  client-main:
    build:
      context: ./client/main
    container_name: one-client-main
    ports:
      - 3000:3000
    stdin_open: true
    volumes:
      - ./client/main:/usr/src/app
      - /usr/src/app/node_modules/
  db-mysql-user:
    container_name: one-db-mysql-user
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: user
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    image: mysql:5.7
    ports:
      - 3306:3306
  ds-main:
    build:
      context: ./ds/main
    container_name: one-ds-main
    ports:
      - 6006:6006
    volumes:
      - ./ds/main:/usr/src/app
      - /usr/src/app/node_modules/
  server-initiative:
    build:
      context: ./server/initiative
    container_name: one-server-initiative
    ports:
      - 9000:3000
    volumes:
      - ./server/initiative:/usr/src/app
      - /usr/src/app/node_modules/
  server-user:
    build:
      context: ./server/user
    container_name: one-server-user
    depends_on:
      db-mysql-user:
        condition: service_healthy
    ports:
      - 9001:3000
    volumes:
      - ./server/user:/usr/src/app
      - /usr/src/app/node_modules/
